version: "3.3"
services:
  app:
    image: polams/guestbookapp:latest
    ports:
      - 8000:8000
    links:
      - db
    depends_on:
      - db
  db:
    image: postgres:12
    environment:
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "guestbook"
      POSTGRES_USER: "postgres"
    ports:
      - 5432:5432
    # restart: always
